### ISSUE TITLE
Crash when pressing the "Config" button from Mod Menu in Neoforge 1.21

### ISSUE THREAD

**Issue by truepurpledino** [blackd/libIPN#21]
On neoforge 21.0.134-beta, having only the base mods installed (IPN, libIPN and kotlin for forge), when clicking on the config button in the Mods menu, the game crashes.

https://mclo.gs/b3q6heL

**Comment by blackd** [comment]
there is nothing in the libIPN config anyway. It exists for testing purposes only.

**Comment by truepurpledino** [comment]
This might be a Neoforge issue, happens on other mods too so nvm

**Comment by truepurpledino** [comment]
Or maybe not? https://github.com/neoforged/NeoForge/issues/1357

**Comment by truepurpledino** [comment]
It also happens in Inventory Profiles Next, which is more important

**Comment by blackd** [comment]
and I thought neoforge will be different and not break things in the same major version of Minecraft.

**Comment by blackd** [comment]
fixed in libIPN 6.0.1 and IPN 2.0.3

**Comment by TelepathicGrunt** [comment]
Neoforge and forge both will do breaking changes as needed during their beta periods. We need to do so in order to actually improve with removing tech debt, refining events, fixing problems, and more.

Neoforge just released our first stable build so if you build against the latest version of Neo, there will be no more breaking changes from here on out until 1.21.1’s release.

**Comment by blackd** [comment]
the minor version can be used to denote breaking changes.
Shows intent and not just some random change. Also helps outside people to know there is a breaking change without needing to follow closely what happens in the project.

I was hoping this will be one of the things that neoforge will change and not just repeate Forge mistakes.
